version: '3.8'

services:
  email-summarizer:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - EMAIL_PORT
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
      - EMAIL_CLIENT_TYPE

networks:
  mcp_network:
    name: mcp_network
